# Dependabot is disabled in favor of Renovate
# See renovate.json and .github/renovate.json5 for dependency management configuration
# This file is kept to prevent accidental re-enabling of Dependabot