name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Install Dependencies, and Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13.x'

      - name: Install Tesseract OCR Engine
        run: |
          sudo apt-get update || exit 1
          sudo apt-get install -y tesseract-ocr tesseract-ocr-eng || exit 1

      - name: Cache pip
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic app setup (creates DB and folders)
        run: |
          cd backend
          python app.py &
          sleep 5
          pkill -f "python app.py" || true

      - name: Run Linting
        run: |
          cd backend
          flake8 .

      - name: Run Tests
        run: |
          cd backend
          pytest
